name: kinsol
favicon: null
layout_spectrum: 0.26321051153354347
typography_spectrum: 0.6517705353908241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7554299284238368
  lightness: 0.9141985331661999
  saturation: 0.10528091504238546
  rhythmicContrast: 0.8606706047430634
purpose: []
