title: Kinetic Solutions
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1052809150423855
  brandStrength: 0.7554299284238368
  lightness: 0.9141985331661999
  brandColors:
    - '#CFBEB4'
    - '#6E5C02'
    - '#5C050C'
    - '#B4A31F'
    - '#303153'
  rhythmicContrast: 0.8606706047430634
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: kinsol
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6517705353908241
layout_spectrum: 1
